/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarievenRouteImport } from './routes/tarieven'
import { Route as SpecialisatiesRouteImport } from './routes/specialisaties'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as OverBrendaRouteImport } from './routes/over-brenda'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BehandelingenRouteImport } from './routes/behandelingen'
import { Route as IndexRouteImport } from './routes/index'

const TarievenRoute = TarievenRouteImport.update({
  id: '/tarieven',
  path: '/tarieven',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialisatiesRoute = SpecialisatiesRouteImport.update({
  id: '/specialisaties',
  path: '/specialisaties',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const OverBrendaRoute = OverBrendaRouteImport.update({
  id: '/over-brenda',
  path: '/over-brenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BehandelingenRoute = BehandelingenRouteImport.update({
  id: '/behandelingen',
  path: '/behandelingen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/behandelingen': typeof BehandelingenRoute
  '/contact': typeof ContactRoute
  '/over-brenda': typeof OverBrendaRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialisaties': typeof SpecialisatiesRoute
  '/tarieven': typeof TarievenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/behandelingen': typeof BehandelingenRoute
  '/contact': typeof ContactRoute
  '/over-brenda': typeof OverBrendaRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialisaties': typeof SpecialisatiesRoute
  '/tarieven': typeof TarievenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/behandelingen': typeof BehandelingenRoute
  '/contact': typeof ContactRoute
  '/over-brenda': typeof OverBrendaRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/specialisaties': typeof SpecialisatiesRoute
  '/tarieven': typeof TarievenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/behandelingen'
    | '/contact'
    | '/over-brenda'
    | '/over-ons'
    | '/sitemap.xml'
    | '/specialisaties'
    | '/tarieven'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/behandelingen'
    | '/contact'
    | '/over-brenda'
    | '/over-ons'
    | '/sitemap.xml'
    | '/specialisaties'
    | '/tarieven'
  id:
    | '__root__'
    | '/'
    | '/behandelingen'
    | '/contact'
    | '/over-brenda'
    | '/over-ons'
    | '/sitemap.xml'
    | '/specialisaties'
    | '/tarieven'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BehandelingenRoute: typeof BehandelingenRoute
  ContactRoute: typeof ContactRoute
  OverBrendaRoute: typeof OverBrendaRoute
  OverOnsRoute: typeof OverOnsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpecialisatiesRoute: typeof SpecialisatiesRoute
  TarievenRoute: typeof TarievenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarieven': {
      id: '/tarieven'
      path: '/tarieven'
      fullPath: '/tarieven'
      preLoaderRoute: typeof TarievenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialisaties': {
      id: '/specialisaties'
      path: '/specialisaties'
      fullPath: '/specialisaties'
      preLoaderRoute: typeof SpecialisatiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-brenda': {
      id: '/over-brenda'
      path: '/over-brenda'
      fullPath: '/over-brenda'
      preLoaderRoute: typeof OverBrendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behandelingen': {
      id: '/behandelingen'
      path: '/behandelingen'
      fullPath: '/behandelingen'
      preLoaderRoute: typeof BehandelingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BehandelingenRoute: BehandelingenRoute,
  ContactRoute: ContactRoute,
  OverBrendaRoute: OverBrendaRoute,
  OverOnsRoute: OverOnsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpecialisatiesRoute: SpecialisatiesRoute,
  TarievenRoute: TarievenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
